"""Structured data contracts and models for the multi-agent investigation system."""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from aletheia.evaluation.models import DiagnosisResult


class EntitySummary(BaseModel):
    """Summary of an entity identified as relevant by the Investigator."""
    model_config = ConfigDict(extra="ignore")

    entity_id: str
    name: str
    type: str
    role: Optional[str] = None
    properties: Dict[str, Any] = Field(default_factory=dict)


class RelationshipSummary(BaseModel):
    """Summary of a causal or temporal relationship identified in the Evidence Graph."""
    model_config = ConfigDict(extra="ignore")

    edge_id: str
    source_id: str
    target_id: str
    type: str
    evidence_ids: List[str] = Field(default_factory=list)
    confidence: float = 1.0


class TimelineEventSummary(BaseModel):
    """Summary of a chronological event in the incident timeline."""
    model_config = ConfigDict(extra="ignore")

    event_id: str
    timestamp: datetime
    type: str
    service: str
    summary: str
    evidence_ids: List[str] = Field(default_factory=list)


class InvestigationObservation(BaseModel):
    """An observation derived from evidence, strictly referencing real evidence IDs."""
    model_config = ConfigDict(extra="ignore")

    observation_id: str
    statement: str
    cited_evidence_ids: List[str] = Field(default_factory=list)
    confidence: float = 1.0


class InvestigationContext(BaseModel):
    """Structured output produced by the Investigator (Phase 6A)."""
    model_config = ConfigDict(extra="ignore")

    incident_id: str
    alert_description: str
    relevant_evidence_ids: List[str] = Field(default_factory=list)
    timeline_events: List[TimelineEventSummary] = Field(default_factory=list)
    important_entities: List[EntitySummary] = Field(default_factory=list)
    relevant_relationships: List[RelationshipSummary] = Field(default_factory=list)
    observations: List[InvestigationObservation] = Field(default_factory=list)
    investigation_summary: str = ""
    hallucinated_ids_rejected: List[str] = Field(default_factory=list)


class Hypothesis(BaseModel):
    """A plausible explanation for an incident generated by the Analyst (Phase 6B)."""
    model_config = ConfigDict(extra="ignore")

    hypothesis_id: str
    hypothesis: str
    suspected_component: Optional[str] = None
    suspected_trigger: Optional[str] = None
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    contradicting_evidence_ids: List[str] = Field(default_factory=list)
    missing_evidence: List[str] = Field(default_factory=list)
    is_causal: bool = True
    confidence: float = Field(default=0.7, ge=0.0, le=1.0)
    rank: int = 1


class AnalystOutput(BaseModel):
    """Structured output produced by the Analyst (Phase 6B)."""
    model_config = ConfigDict(extra="ignore")

    incident_id: str
    hypotheses: List[Hypothesis] = Field(default_factory=list)
    correlation_vs_causation_notes: str = ""
    analysis_summary: str = ""


class HypothesisChallenge(BaseModel):
    """Scrutiny applied by the Verifier (Phase 6C) against an Analyst hypothesis."""
    model_config = ConfigDict(extra="ignore")

    hypothesis_id: str
    passed_verification: bool
    temporal_ordering_valid: bool = True
    temporal_ordering_notes: str = ""
    causal_claims_supported: bool = True
    causal_support_notes: str = ""
    contradictions_detected: List[str] = Field(default_factory=list)
    missing_critical_evidence: List[str] = Field(default_factory=list)
    challenge_notes: str = ""


class VerifierOutput(BaseModel):
    """Structured output produced by the Verifier (Phase 6C)."""
    model_config = ConfigDict(extra="ignore")

    incident_id: str
    verdict: str  # "verified", "insufficient_evidence", "all_hypotheses_rejected"
    challenges: List[HypothesisChallenge] = Field(default_factory=list)
    best_hypothesis: Optional[Hypothesis] = None
    final_diagnosis: Optional[DiagnosisResult] = None
    verification_summary: str = ""
