import { IncidentMetadata, BenchmarkSystemSummary } from "./types";

export const INITIAL_INCIDENTS: IncidentMetadata[] = [
  {
    incident_id: "INC-001",
    name: "Database Query Regression (Unindexed Scan)",
    category: "database_regression",
    severity: "CRITICAL",
    affected_service: "checkout-api",
    description: "Checkout latency spiked from 45ms to 1800ms following release v4.2.1 due to missing orders index.",
  },
  {
    incident_id: "INC-002",
    name: "Unbounded Memory Cache Leak in Checkout Worker",
    category: "memory_leak",
    severity: "CRITICAL",
    affected_service: "checkout-worker",
    description: "Python worker memory climbed linearly to 995MB triggering OOMKilled events.",
  },
  {
    incident_id: "INC-003",
    name: "Third-Party Payment Gateway Latency Spike and 504s",
    category: "external_api_latency",
    severity: "HIGH",
    affected_service: "payment-gateway",
    description: "External payment vendor AcmePay downstream latency spiked past 10s causing 504 timeouts.",
  },
  {
    incident_id: "INC-004",
    name: "Release Missing Database Schema Column",
    category: "bad_deployment",
    severity: "CRITICAL",
    affected_service: "checkout-api",
    description: "Release v4.2.3 deployed prior to database migration causing UndefinedColumn exceptions.",
  },
  {
    incident_id: "INC-005",
    name: "Database Connection Pool Throttled to 1",
    category: "configuration_error",
    severity: "HIGH",
    affected_service: "checkout-api",
    description: "DB_POOL_SIZE misconfigured to 1 in deployment manifest causing thread lockups.",
  },
  {
    incident_id: "INC-006",
    name: "Postgres Connection Pool Saturation",
    category: "connection_exhaustion",
    severity: "HIGH",
    affected_service: "checkout-api",
    description: "Leaked database client sessions exhausted maximum connection limit (100/100).",
  },
  {
    incident_id: "INC-007",
    name: "CPU Saturation from ReDoS Regex Evaluation",
    category: "cpu_saturation",
    severity: "HIGH",
    affected_service: "checkout-api",
    description: "Catastrophic backtracking in promo code regex pinned CPU at 100%.",
  },
  {
    incident_id: "INC-008",
    name: "Cascading Upstream Service Saturation",
    category: "cascading_failure",
    severity: "CRITICAL",
    affected_service: "inventory-service",
    description: "Inventory API timeout cascading downstream to cart and checkout services.",
  },
  {
    incident_id: "INC-009",
    name: "Simultaneous Deployment and DB Failure",
    category: "simultaneous_failure",
    severity: "CRITICAL",
    affected_service: "checkout-api",
    description: "Database storage failure coincident with minor frontend release.",
  },
  {
    incident_id: "INC-010",
    name: "Misleading CPU Alert Masking Downstream Lock",
    category: "misleading_symptoms",
    severity: "MEDIUM",
    affected_service: "checkout-api",
    description: "CPU alert triggered while root cause is row-level database lock.",
  },
  {
    incident_id: "INC-011",
    name: "Silent Tracing Drop During Partial Outage",
    category: "missing_evidence",
    severity: "HIGH",
    affected_service: "checkout-api",
    description: "Telemetry collector dropped spans under high volume, hiding failure traces.",
  },
  {
    incident_id: "INC-012",
    name: "Clock Skew Contradicting Causal Ordering",
    category: "contradictory_evidence",
    severity: "MEDIUM",
    affected_service: "checkout-api",
    description: "Host NTP drift made effect timestamps appear before root cause deployment.",
  },
  {
    incident_id: "INC-013",
    name: "Obsolete Runbook Suggesting Wrong Failover",
    category: "stale_documentation",
    severity: "LOW",
    affected_service: "checkout-api",
    description: "Outdated documentation suggested restarting Redis instead of Postgres.",
  },
  {
    incident_id: "INC-014",
    name: "Hostile Log Payload Attempting Agent Injection",
    category: "prompt_injection",
    severity: "CRITICAL",
    affected_service: "checkout-api",
    description: "User agent header injected malicious instruction into diagnostic prompt context.",
  },
  {
    incident_id: "INC-015",
    name: "Internal Tool Exception During Diagnostics",
    category: "tool_api_failure",
    severity: "HIGH",
    affected_service: "diagnostic-worker",
    description: "Diagnostic query tool threw unhandled socket error during log retrieval.",
  },
  {
    incident_id: "INC-016",
    name: "Redis Cache Eviction Cascading to Database",
    category: "cascading_failure",
    severity: "HIGH",
    affected_service: "checkout-api",
    description: "Cache maxmemory eviction triggered thundering herd query surge on Postgres.",
  },
  {
    incident_id: "INC-017",
    name: "Distributed Deadlock on Order Status Update",
    category: "deadlock",
    severity: "HIGH",
    affected_service: "checkout-api",
    description: "Concurrent updates across orders and shipments resulted in deadlocked transactions.",
  },
  {
    incident_id: "INC-018",
    name: "Disk Volume 100% Full Preventing WAL Write",
    category: "disk_exhaustion",
    severity: "CRITICAL",
    affected_service: "postgresql",
    description: "Unarchived WAL segment accumulation consumed 100% of the partition.",
  },
  {
    incident_id: "INC-019",
    name: "DNS Server Failure Causing Internal RPC Drop",
    category: "network_failure",
    severity: "CRITICAL",
    affected_service: "checkout-api",
    description: "CoreDNS pod crash caused name resolution failures across internal microservices.",
  },
  {
    incident_id: "INC-020",
    name: "Schema Drift Between Staging and Production",
    category: "schema_drift",
    severity: "HIGH",
    affected_service: "checkout-api",
    description: "Unapplied migration created table discrepancy between staging and prod.",
  },
];

export const BENCHMARK_SUMMARIES: Record<string, BenchmarkSystemSummary> = {
  "Baseline-A (Single-LLM)": {
    system_name: "Baseline A (Single-LLM)",
    total_incidents: 20,
    passed_evaluations: 1,
    failed_evaluations: 19,
    mean_overall_score: 0.221,
    mean_root_cause_accuracy: 0.465,
    top_3_hypothesis_accuracy: 1.0,
    mean_evidence_recall: 0.496,
    mean_evidence_precision: 0.738,
    hallucination_rate: 0.95,
    false_positive_rate: 0.70,
    verification_success_rate: 0.05,
    mean_latency_seconds: 0.000,
  },
  "Baseline-B (2-Agent)": {
    system_name: "Baseline B (2-Agent)",
    total_incidents: 20,
    passed_evaluations: 9,
    failed_evaluations: 11,
    mean_overall_score: 0.655,
    mean_root_cause_accuracy: 0.680,
    top_3_hypothesis_accuracy: 0.95,
    mean_evidence_recall: 0.562,
    mean_evidence_precision: 1.0,
    hallucination_rate: 0.0,
    false_positive_rate: 0.30,
    verification_success_rate: 0.15,
    mean_latency_seconds: 0.000,
  },
  "Aletheia (3-Agent)": {
    system_name: "Aletheia (3-Agent)",
    total_incidents: 20,
    passed_evaluations: 9,
    failed_evaluations: 11,
    mean_overall_score: 0.661,
    mean_root_cause_accuracy: 0.695,
    top_3_hypothesis_accuracy: 0.95,
    mean_evidence_recall: 0.562,
    mean_evidence_precision: 1.0,
    hallucination_rate: 0.0,
    false_positive_rate: 0.25,
    verification_success_rate: 1.0,
    mean_latency_seconds: 0.001,
  },
};
